version: "3.8"

services:

  api:
    image: cognos-api:latest
    container_name: cognos-api
    restart: unless-stopped
    environment:
      - COGNOS_USER=${COGNOS_USER}
      - COGNOS_PASS=${COGNOS_PASS}
      - COGNOS_DSN=${COGNOS_DSN}
      - COGNOS_NOME_VIEW=${COGNOS_NOME_VIEW}
      - COGNOS_NOME_COGNOS=${COGNOS_NOME_COGNOS}
      - COGNOS_NOME_NEGOCIO=${COGNOS_NOME_NEGOCIO}
      - COGNOS_DATA_SOURCE=${COGNOS_DATA_SOURCE}
      - COGNOS_VL_EVENT_CAMPO=${COGNOS_VL_EVENT_CAMPO}
      - ALLOWED_ORIGINS=http://localhost,http://localhost:80
    networks:
      - cognos-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: cognos-frontend:latest
    container_name: cognos-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - cognos-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  cognos-net:
    driver: overlay
